### ISSUE TITLE
adapt `data` folder

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/lifewatch-meeting-2018#11]
```
data
|- external  #external geojson
|- interim  # downloaded data
|- processed  # final data set
|- raw (as we download all script based, we do not need this for this project
```

**Comment by damianooldoni** [comment]
branch `adapt_data_folder_rgbif_final` made and relative links in RGBIF tutorial have been done.
`wind_speed.rda` and `wind_direction.rda` related to wateRinfo tutorial are put in `interim`.
@stijnvanhoey : can you check the relative paths in wateRinfo tutorial if any (I don't find any `load("wind_speed.rda")` or `load("wind_direction.rda"` in your notebook)? And could you get a final look to the data folder structure, then close issue and merge to master? 
Thanks
Damiano

**Comment by stijnvanhoey** [comment]
Nice work! data folder is now consistent with our other work.
The `*.rda` data sets are there - just in case - so, no path adaptations required. thanks!
